// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var fs, isGlob, Path;
  fs = require('fs');
  Path = require('path');
  exports.glob = require('glob');
  exports.getGlobPattern = function (basePath, options) {
    var cache$, extension, fuzz, path, recursive;
    if (options.absolute === true)
      basePath = Path.resolve(basePath);
    if (isGlob(basePath))
      return basePath;
    cache$ = options;
    extension = cache$.extension;
    recursive = cache$.recursive;
    fuzz = recursive !== false ? '**/*' : '*';
    path = '' + basePath + '/' + fuzz;
    if (null != extension)
      path += '.' + extension;
    return Path.normalize(path);
  };
  exports.isFile = function (path) {
    return fs.statSync(path).isFile();
  };
  exports.isString = function (obj) {
    return {}.toString.call(obj) === '[object String]';
  };
  isGlob = function (str) {
    return str.indexOf('*') !== -1;
  };
}.call(this);
